version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch
    ports: ['9200:9200']
    networks:
      elastic:
        aliases:
          - elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports: [ '5601:5601' ]
    networks: ['elastic']

networks:
  elastic:
    driver: bridge
